kind: pipeline
type: docker
name: haproxy-wi-docker

steps:
  - name: restore-cache-with-filesystem
    image: meltwater/drone-cache:v1.1
    settings:
      restore: true
      backend: "filesystem"
      cache_key: '{{ .Repo.Name }}_{{ checksum "composer.lock" }}_v1'
      archive_format: "gzip"
      mount:
        - 'vendor'
    volumes:
      - name: DroneIO-Cache
        path: /tmp/cache

  - name: rebuild-cache-with-filesystem
    image: meltwater/drone-cache:v1.1
    settings:
      rebuild: true
      backend: "filesystem"
      cache_key: '{{ .Repo.Name }}_{{ checksum "composer.lock" }}_v1'
      archive_format: "gzip"
      mount:
        - 'vendor'
    volumes:
      - name: DroneIO-Cache
        path: /tmp/cache

  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: saaq.whnet.ca/samuelleb11/haproxy-wi-docker
      cache_from: "saaq.whnet.ca/samuelleb11/haproxy-wi-docker:0.0.1"
      registry: saaq.whnet.ca
      tags:
        - 0.0.1

volumes:
  - name: DroneIO-Cache
    host:
      path: /var/lib/cache
